/* Generated by scripts/wordmark-centerlines.mjs — do not edit by hand.
 *
 * One entry per brush stroke in public/wordmark.svg, recovered by skeletonizing
 * the filled art (see the script).
 *
 *   d      the line the pen travelled, in viewBox units, in writing direction
 *   width  how fat a mask stroke has to be to uncover that stroke completely
 *   len    how far the pen travels, for pacing long strokes against short ones
 *
 * WordmarkDraw sweeps `d` as a mask to trace the lettering on.
 */
export const WORDMARK_CENTERLINES = {
  0: { d: 'M8 64L14 58L14 68L26 78L28 66L30 70L28 82L40 144L54 160L66 276L56 162L68 150L70 126L78 120L78 92L78 116L94 128L118 206L132 216L136 256L134 218L142 210L144 200L146 142L154 96L154 88L144 90L154 86L146 70', width: 54.7, len: 852 },
  1: { d: 'M188 62L188 258L198 270', width: 44.1, len: 212 },
  2: { d: 'M206 156L276 138', width: 47.1, len: 72 },
  3: { d: 'M254 48L258 82L254 264L264 280', width: 45.6, len: 235 },
  4: { d: 'M282 260L284 252L288 260L286 250L328 66L340 56L352 64L358 76L390 170L406 204L416 244L430 254', width: 62.3, len: 455 },
  5: { d: 'M330 150L386 156L400 162L414 162L420 156', width: 41, len: 94 },
  6: { d: 'M642 50L642 62L648 50L640 72L644 92L642 176L650 184L646 236L652 184L666 196L674 196L654 182L684 162L688 138L684 164L692 172L694 198L712 214L718 246L710 208L720 192L726 110L728 24L720 12', width: 54.7, len: 741 },
  7: { d: 'M96 360L106 352L166 332L198 328L210 334L198 326L206 318L216 318L220 326', width: 44.1, len: 166 },
  8: { d: 'M172 348L168 554L162 570L164 582L162 572L144 558', width: 44.1, len: 268 },
  9: { d: 'M294 320L274 324L256 336L226 518L226 544L236 548L284 526L292 516L292 508', width: 39.5, len: 337 },
  10: { d: 'M264 420L292 408', width: 36.5, len: 30 },
  11: { d: 'M722 348L832 340', width: 38, len: 110 },
  12: { d: 'M784 364L784 432L780 478L776 484L776 510L784 518', width: 42.6, len: 159 },
  13: { d: 'M750 528L756 524L828 516', width: 41, len: 80 },
  14: { d: 'M588 586L610 510L622 432L636 432L624 426L630 392L642 372L642 352L644 374L658 382L664 400L700 546', width: 44.1, len: 471 },
  15: { d: 'M610 488L710 458L718 446', width: 38, len: 119 },
  16: { d: 'M832 22L820 20L828 16L768 20L764 26L768 88L756 90L766 88L770 92L776 234L782 238L790 236L832 214L838 198', width: 53.2, len: 401 },
  17: { d: 'M772 120L816 122', width: 42.6, len: 44 },
  18: { d: 'M410 46L528 14L542 2', width: 42.6, len: 141 },
  19: { d: 'M466 32L468 36L462 44L464 72L472 100L488 222L486 228L470 234', width: 45.6, len: 218 },
  20: { d: 'M346 346L350 392L350 532L354 536L372 530L386 522L394 510', width: 56.2, len: 241 },
  21: { d: 'M426 332L428 336L422 344L424 568L430 574L452 572L460 562', width: 36.5, len: 282 },
};
