/* Generated by scripts/wordmark-centerlines.mjs — do not edit by hand.
 *
 * One entry per brush stroke in public/wwtai_2.svg, in writing order.
 *
 *   i         which path in the SVG this stroke is, so the art and the
 *             centerline (see wordmarkCenterlines.js) can be paired up
 *   x y w h   the stroke's bounding box in viewBox units, used to size its
 *             mask — a mask that covers the whole canvas per stroke is 31x the
 *             fill rate for no gain
 */
export const WORDMARK_VIEWBOX = '0 0 2461 456';

export const WORDMARK_STROKES = [
  { i: 12, x: 0, y: 100, w: 218, h: 356 },
  { i: 13, x: 160, y: 214, w: 134, h: 212 },
  { i: 14, x: 234, y: 66, w: 68, h: 350 },
  { i: 0, x: 304, y: 102, w: 96, h: 296 },
  { i: 1, x: 354, y: 196, w: 136, h: 82 },
  { i: 2, x: 416, y: 74, w: 60, h: 336 },
  { i: 3, x: 490, y: 102, w: 210, h: 320 },
  { i: 10, x: 562, y: 26, w: 270, h: 70 },
  { i: 4, x: 548, y: 240, w: 144, h: 76 },
  { i: 11, x: 672, y: 30, w: 96, h: 358 },
  { i: 25, x: 888, y: 114, w: 106, h: 274 },
  { i: 26, x: 958, y: 234, w: 70, h: 154 },
  { i: 27, x: 974, y: 236, w: 100, h: 158 },
  { i: 28, x: 1040, y: 76, w: 58, h: 304 },
  { i: 15, x: 1122, y: 88, w: 88, h: 304 },
  { i: 16, x: 1120, y: 94, w: 186, h: 62 },
  { i: 17, x: 1148, y: 214, w: 140, h: 62 },
  { i: 18, x: 1124, y: 352, w: 148, h: 54 },
  { i: 23, x: 1350, y: 20, w: 250, h: 124 },
  { i: 24, x: 1436, y: 70, w: 78, h: 358 },
  { i: 19, x: 1582, y: 80, w: 124, h: 84 },
  { i: 20, x: 1542, y: 112, w: 76, h: 276 },
  { i: 21, x: 1570, y: 186, w: 142, h: 94 },
  { i: 22, x: 1576, y: 322, w: 148, h: 76 },
  { i: 29, x: 1726, y: 26, w: 118, h: 352 },
  { i: 30, x: 1854, y: 14, w: 142, h: 372 },
  { i: 8, x: 2064, y: 0, w: 232, h: 384 },
  { i: 9, x: 2114, y: 182, w: 190, h: 88 },
  { i: 5, x: 2300, y: 58, w: 160, h: 54 },
  { i: 6, x: 2346, y: 82, w: 62, h: 254 },
  { i: 7, x: 2294, y: 312, w: 136, h: 48 },
];
