/* Generated by scripts/wordmark-centerlines.mjs — do not edit by hand.
 *
 * One entry per brush stroke in public/wwtai_2.svg, recovered by skeletonizing
 * the filled art (see the script).
 *
 *   d      the line the pen travelled, in viewBox units, in writing direction
 *   width  how fat a mask stroke has to be to uncover that stroke completely
 *   len    how far the pen travels, for pacing long strokes against short ones
 *
 * WordmarkDraw sweeps `d` as a mask to trace the lettering on.
 */
export const WORDMARK_CENTERLINES = {
  0: { d: 'M334 102L332 138L348 194L366 338L372 358L392 378L388 392', width: 76, len: 303 },
  1: { d: 'M408 262L394 238L448 226L480 202', width: 91.2, len: 123 },
  2: { d: 'M452 74L454 84L442 98L448 136L444 376L462 402', width: 69.9, len: 339 },
  3: { d: 'M504 420L502 406L518 390L518 368L538 306L560 184L582 164L612 190L632 262L650 290L662 332L680 334L682 348L698 366', width: 142.9, len: 525 },
  4: { d: 'M562 280L588 270L658 284L666 314', width: 80.6, len: 130 },
  5: { d: 'M2328 82L2420 86L2422 110', width: 83.6, len: 116 },
  6: { d: 'M2380 82L2374 110L2382 142L2374 308L2392 326L2388 332', width: 73, len: 260 },
  7: { d: 'M2304 338L2410 334L2428 350', width: 59.3, len: 130 },
  8: { d: 'M2072 378L2096 348L2126 280L2174 114L2206 92L2206 20L2218 2L2208 94L2232 122L2256 288L2282 318L2284 354', width: 94.2, len: 791 },
  9: { d: 'M2114 232L2252 216L2298 182', width: 86.6, len: 196 },
  10: { d: 'M570 30L598 56L716 58L802 72L830 52', width: 79, len: 278 },
  11: { d: 'M706 32L698 70L716 144L738 334L738 352L724 368L706 368', width: 77.5, len: 364 },
  12: { d: 'M20 100L28 110L28 130L94 242L130 324L166 342L150 254L174 270L176 334L168 346L190 412L186 428L202 450L212 442', width: 95.8, len: 615 },
  13: { d: 'M186 220L196 232L196 260L250 376L276 406L286 406', width: 74.5, len: 221 },
  14: { d: 'M258 88L274 344L280 394L296 408', width: 59.3, len: 328 },
  15: { d: 'M1184 94L1170 104L1180 126L1146 352L1168 390', width: 79, len: 314 },
  16: { d: 'M1148 126L1156 120L1280 126L1304 104', width: 76, len: 167 },
  17: { d: 'M1170 250L1184 240L1264 242L1286 220', width: 74.5, len: 128 },
  18: { d: 'M1150 374L1228 378L1236 392', width: 76, len: 94 },
  19: { d: 'M1628 150L1616 126L1676 110L1698 82', width: 85.1, len: 125 },
  20: { d: 'M1576 112L1566 146L1576 182L1584 324L1590 360L1616 378', width: 71.4, len: 283 },
  21: { d: 'M1606 252L1608 240L1672 216L1704 194', width: 80.6, len: 119 },
  22: { d: 'M1576 376L1682 350L1698 340L1704 324', width: 57.8, len: 145 },
  23: { d: 'M1362 142L1378 114L1404 102L1482 82L1558 50L1594 50', width: 73, len: 260 },
  24: { d: 'M1464 70L1460 90L1474 204L1474 348L1482 400L1498 416L1510 410', width: 73, len: 368 },
  25: { d: 'M920 118L916 156L956 330L966 360L986 378', width: 71.4, len: 275 },
  26: { d: 'M1002 236L1010 254L994 292L980 360', width: 63.8, len: 130 },
  27: { d: 'M1014 252L1010 270L1040 350L1068 372', width: 83.6, len: 139 },
  28: { d: 'M1070 78L1080 104L1068 158L1060 362', width: 48.6, len: 287 },
  29: { d: 'M1784 26L1786 34L1772 50L1756 338L1822 332L1838 310', width: 86.6, len: 411 },
  30: { d: 'M1882 16L1888 20L1882 58L1894 140L1894 344L1940 344L1964 322L1974 326L1980 318', width: 88.2, len: 432 },
};
